development:
  adapter: postgresql
  encoding: utf8
  database: frankeinstein_development
  pool: 5


test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: frankeinstein_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: frakeinstein_app
  pool: 5
