# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 587a74f8e71c8368c80d2bff52ec95b379d67a88249af5ea5d3d71faf5ee1f737aaa23775b4417fb890d9fbfe2c3c941095c8b81e8e96a5d2097c5f67a7eb0db

test:
  secret_key_base: 3695ad6c80be4e2ea503749e3ecab2018f0d4c7178b03a70e3fec1b693a61357db946a4ad3027e30a38fda6e562e1b61e09ed8dd0bacdb434a01e7f9c5996998

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
